config/routes.rb
Rails.application.routes.draw do
  root to: 'dashboards#show'

  resource :dkim, only: [:show, :new, :create]
  resource :spf, only: [:show, :new, :create]
  resource :lookup, only: [:show, :new, :create]
  resource :dashboard, only: :show
  resource :location, only: [:new, :create]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_to_dashboard
  protect_from_forgery with: :exception

  def redirect_to_dashboard
    if params[:action] == 'show' && params[:controller] != 'dashboards'
      redirect_to root_path
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
end

app/controllers/dkims_controller.rb
class DkimsController < ApplicationController
  def show; end

  def create
    dkim_service.call
  end

  private
  def dkim_service
    @dkim_service ||= DNS::DKIMService.new(*dkim_service_params)
  end
  helper_method :dkim_service

  def dkim_service_params
    params.require(:dkim).permit(:domain_name, :selector).values
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  respond_to :js, only: :create

  def create
    @location = Geokit::Geocoders::MultiGeocoder.geocode(params[:location][:address])
    respond_with @location, layout: false
  end
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  def show; end

  def create
    lookup_service.call
  end

  private
  def lookup_service
    @lookup_service ||= DNS::LookupService.new(*lookup_service_params)
  end
  helper_method :lookup_service

  def lookup_service_params
    params.require(:lookup).permit(:address).values
  end
end

app/controllers/spfs_controller.rb
class SpfsController < ApplicationController
  def show; end

  def create
    spf_service.call
  end

  private
  def spf_service
    @spf_service ||= DNS::SPFService.new(*spf_service_params)
  end
  helper_method :spf_service

  def spf_service_params
    params.require(:spf).permit(:address, :domain_name).values
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboards/show.slim
ul
  li.wrapper = link_to t('dashboard.first'), new_lookup_path, class: 'sixth before after'
  li.wrapper = link_to t('dashboard.second'), new_dkim_path, class: 'sixth before after'
  li.wrapper = link_to t('dashboard.third'), new_spf_path, class: 'sixth before after'
  li.wrapper = link_to t('dashboard.location'), new_location_path, class: 'sixth before after'

app/views/dkims/create.slim
= render 'shared/errors', errors: dkim_service.errors

h3 = t('labels.args')
= render partial: 'shared/coll', collection: params[:dkim].values

- if dkim_service.result?
  h3 = t('labels.result')
  = render partial: 'shared/coll', collection: dkim_service.result

  h3 = t('labels.keys')
  = render partial: 'shared/coll', collection: dkim_service.keys
- else
  h3 = t('labels.nothing')
  
= link_to t('links.back'), new_dkim_path

app/views/dkims/new.slim
.form-wrapper
  p.task-title.no-margin Second Task
  = simple_form_for :dkim, url: dkim_path do |f|
    = f.input :domain_name, required: false
    = f.input :selector, required: false
    = f.submit t('buttons.search')
.back
  = link_to t('links.back'), root_path

app/views/layouts/application.slim
doctype html
html
  head
    title DnsTest
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'https://api-maps.yandex.ru/2.1/?lang=en_US'
  body
    = yield

app/views/locations/create.js.erb
drawMap([<%= @location.lat %>, <%= @location.lng %>], '<%= params[:location][:address] %>');

app/views/locations/new.slim
.form-wrapper
  p.task-title.no-margin Location
  = simple_form_for :location, url: location_path, remote: true do |f|
    = f.input :address, required: false
    = f.submit t('buttons.search')
#map
.back
  = link_to t('links.back'), root_path

app/views/lookups/create.slim
= render 'shared/errors', errors: lookup_service.errors

h3 = t('labels.args')
= render partial: 'shared/coll', collection: params[:lookup].values

- if lookup_service.result?
  h3 = t('labels.result')
  = render partial: 'shared/coll', collection: lookup_service.result
- else
  h3 = t('labels.nothing')
  
= link_to t('links.back'), new_lookup_path

app/views/lookups/new.slim
.form-wrapper
  p.task-title.no-margin First Task
  = simple_form_for :lookup, url: lookup_path do |f|
    = f.input :address, required: false, label: 'IP Address'
    = f.submit t('buttons.lookup')
.back
  = link_to t('links.back'), root_path

app/views/shared/_coll.slim
p = coll

app/views/shared/_errors.slim
div.errors
  - errors.each do |e|
    p
      span.error-msg = e

app/views/shared/_result.slim
- if service.result?
  h3 = t('labels.result')
  = render partial: 'shared/coll', collection: service.result

app/views/spfs/create.slim
= render 'shared/errors', errors: spf_service.errors

h3 = t('labels.args')
= render partial: 'shared/coll', collection: params[:spf].values
- if spf_service.result?
  h3 = t('labels.result')
  = render partial: 'shared/coll', collection: spf_service.result

  h3 = t('labels.is_valid')
  p
    = spf_service.valid?

  h3 = t('labels.is_listed')
  p
    = spf_service.listed?
  = render partial: 'shared/coll', collection: spf_service.listed
- else
  h3 = t('labels.nothing')

= link_to t('links.back'), new_spf_path

app/views/spfs/new.slim
.form-wrapper
  p.task-title.no-margin Third Task
  = simple_form_for :spf, url: spf_path do |f|
    = f.input :address, required: false, label: 'IP Address'
    = f.input :domain_name, required: false
    = f.submit t('buttons.search')
.back
  = link_to t('links.back'), root_path